site_name: XCRI Toolkit Docs
site_url: https://xsede.org/xcri
site_description: XCRI Toolkit documentation

repo_url: https://github.com/XSEDE/XCRI-Docs

docs_dir: docs

pages:
- Home: 'index.md'
- Toolkits:
  - XCBC: 'toolkits/xcbc.md'
    - Virtual Machine Tutorial: 'toolkits/xcbc-installation.md'
    - GPU Node Build: 'toolkits/gpu-nodes.md'
    - Compute Node Modification: 'toolkits/compute-node-mods.md'
    - Slurmdbd Configuration: 'toolkits/slurmdbd-config.md'
  - Cluster Monitoring Toolkit: 'toolkits/clustermon.md'
    - Installation: 'toolkits/clustermon-installation.md'
    - Configuration: 'toolkits/clustermon-config.md'
  - XNIT: 'toolkits/xnit.md'
    - Installation: 'toolkits/xnit-installation.md'
  - Jetstream VC: 'toolkits/vc.md'
    - Installation: 'toolkits/vc-installation.md'
- Contact Us: 'contact-us.md'

theme: readthedocs

#extra_css:
#  - css/extra.css

markdown_extensions:
  - toc:
     permalink: 
- admonition
